apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-ui.fullname" . }}
  namespace: {{ template "web-ui.namespace" . }}
  labels:
    {{- include "web-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "web-ui.fullname" . }}
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
          - key: auth.lua
            path: auth.lua
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: nginx-config
            mountPath: /usr/local/etc/haproxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.global.ingress.enabled }}
          {{- if .Values.global.certificate.enabled }}
          - name: TENANT_MANAGER_URL
            value: "https://{{ .Values.global.domains.tenantManager }}:{{ .Values.global.ingressSecurePort }}"
          - name: AUDIT_BACKEND_URL
            value: "https://{{ .Values.global.domains.auditBackend }}:{{ .Values.global.ingressSecurePort }}"
          - name: ESO_SERVER_URL
            value: "https://{{ .Values.global.domains.esoServer }}:{{ .Values.global.ingressSecurePort }}"
          - name: WEBSITE_URL
            value: "https://{{ .Values.global.domains.webUi }}:{{ .Values.global.ingressSecurePort }}"
          - name: WEB_UI_URL
            value: "https://{{ .Values.global.domains.webUi }}:{{ .Values.global.ingressSecurePort }}"
          {{- else }}
          - name: TENANT_MANAGER_URL
            value: "http://{{ .Values.global.domains.tenantManager }}:{{ .Values.global.ingressPort }}"
          - name: AUDIT_BACKEND_URL
            value: "http://{{ .Values.global.domains.auditBackend }}:{{ .Values.global.ingressPort }}"
          - name: ESO_SERVER_URL
            value: "http://{{ .Values.global.domains.esoServer }}:{{ .Values.global.ingressPort }}"
          - name: WEBSITE_URL
            value: "http://{{ .Values.global.domains.webUi }}:{{ .Values.global.ingressPort }}"
          - name: WEB_UI_URL
            value: "http://{{ .Values.global.domains.webUi }}:{{ .Values.global.ingressPort }}"
          {{- end }}
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.extraArgs }}
          args:
          {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
          - --{{ $key }}={{ $value }}
            {{- else }}
          - --{{ $key }}
            {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
