worker_processes 1;
error_log /dev/stderr info;
# Run Nginx as the haproxy user
user haproxy;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    include       mime.types;      # Include MIME types
    default_type  application/octet-stream;

    server {
        listen 8081;

        root /usr/share/web-ui/html;

        # Handle SPA routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Optional: Serve correct MIME types for JavaScript modules
        location ~* \.js$ {
            types { }
            default_type application/javascript;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/web-ui/html;
        }
    }
}
