name: Commit Message check

on:
  pull_request:
    branches:
      - main

jobs:
  conventional-commit:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: check
      uses: ahmadnassri/action-commit-lint@v2
      with:
        config: conventional
