name: Label PR based on size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr:
    permissions:
      pull-requests: write
      issues: write
      contents: read
    uses: external-secrets-inc/actions/.github/workflows/label.yaml@main
    with:
      ignore_list: 'package-lock.json, go.mod, go.sum, README.md'
      ignore_dirs: 'docs/'
    secrets:
      ESI_BOT_PRIVATE_KEY: ${{ secrets.ESI_BOT_PRIVATE_KEY }}
